name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: CI builder for listenbrainz-rs

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Perform build of listenbrainz-rs
      run: cargo build --verbose
    - name: Run unit tests for listenbrain-rs
      run: cargo test --verbose

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minimal toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Run rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --document-private-items
